default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>

development:
  <<: *default
  database: connectxbot_development
  username: connectxbot
  password: password

test:
  <<: *default
  database: connectxbot_test
  username: connectxbot
  password: password
