default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: connectxbot_development
  username: connectxbot
  password: password

test:
  <<: *default
  database: connectxbot_test
  username: connectxbot
  password: <%= ENV['CONNECTXBOT_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: connectxbot_production
  username: connectxbot
  password: <%= ENV['CONNECTXBOT_DATABASE_PASSWORD'] %>
